### ISSUE TITLE
Questions about flow

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/write-a-ll-course#11]
Hello @hectorsector! 👋 I ❤️ this course, and I think it's a really nice introduction to writing courses. Here are a few questions I have about the flow:

- What is accomplished by having an issue, rather than starting the course off in a PR? If the PR already existed, and the starting info was there, then we could immediately jump in. Is the problem that we can't do suggested edits?
- Everything in one PR makes _sense_, but it's a lot to scroll through and it's ending up being difficult to find exactly what I should be doing. Are there an logical break points?
- We throw `'%payload.pull_request.title%'` at them without introducing it first. Is there a way we can do two introductions here, or introduce those concepts separately?

**Comment by hectorsector** [comment]
Thanks for spending some time on the course @brianamarie! 

> What is accomplished by having an issue, rather than starting the course off in a PR? If the PR already existed, and the starting info was there, then we could immediately jump in. Is the problem that we can't do suggested edits?

When the bot opens the PR, it cannot approve its own PR. I realize the bot currently doesn’t approve it, but my intention was always to protect the master branch and then have the bot approve at the end. In order for this to happen, the learner must open the PR.  We could  skip the welcome issue step  by having the bot opening the PR, however it would then mean that we would have to remove and reapply brand protections which I don’t love as a practice, or get creative about mergability. Another upside of a bot-created PR is that we could also define the title of the pull request. Currently we can only demand that the learner use a specific title which we need for referencing the pull request later on. 

> Everything in one PR makes sense, but it's a lot to scroll through and it's ending up being difficult to find exactly what I should be doing. Are there an logical break points?

I’m torn on this one and open to suggestions. One piece of feedback we got on the Actions course is that it was easy to have everything in a single PR. However I see your point that in this course it might be too much in a single PR. 

> We throw '%payload.pull_request.title%' at them without introducing it first. Is there a way we can do two introductions here, or introduce those concepts separately?

Sure, how might that work?

**Comment by hectorsector** [comment]
> > Everything in one PR makes sense, but it's a lot to scroll through and it's ending up being difficult to find exactly what I should be doing. Are there an logical break points?
> 
> I’m torn on this one and open to suggestions. One piece of feedback we got on the Actions course is that it was easy to have everything in a single PR. However I see your point that in this course it might be too much in a single PR.

Some possible breakpoints are:
1. Metadata (steps 1-2)
1. Repo setup (steps 3-6)
1. Write steps (steps 7-11)
1. Get ready for publishing (steps 12-14)

**Comment by brianamarie** [comment]
> When the bot opens the PR, it cannot approve its own PR. I realize the bot currently doesn’t approve it, but my intention was always to protect the master branch and then have the bot approve at the end. In order for this to happen, the learner must open the PR. We could skip the welcome issue step by having the bot opening the PR, however it would then mean that we would have to remove and reapply brand protections which I don’t love as a practice, or get creative about mergability. Another upside of a bot-created PR is that we could also define the title of the pull request. Currently we can only demand that the learner use a specific title which we need for referencing the pull request later on.
> 
> >

There are a lot of pros and cons here. 🤔 I think I'm in favor of having the Bot open the PR, even though it would mean some creative branch protections, because I think every step should be meaningful in the behavior we're asking the user to complete. On the other hand, could we use another trigger that is more meaningful to the content of the course? Instead of having the user close the issue, maybe we try to prompt them for what they'd like to teach, and use their comment as a trigger? It would keep the same flow, but start to get the user thinking about something course-related. 

> Some possible breakpoints are:
> 
> 1. Metadata (steps 1-2)
> 2. Repo setup (steps 3-6)
> 3. Write steps (steps 7-11)
> 4. Get ready for publishing (steps 12-14)

😍 I like this, I think it's worth exploring. It would give the user more places to look, which could be confusing. BUT, I really like how you break this down into these four categories. It makes the whole concept of building a config more approachable and easier to think about, _and_ it will make each PR more manageable. 

> > We throw '%payload.pull_request.title%' at them without introducing it first. Is there a way we can do two introductions here, or introduce those concepts separately?
> 
> Sure, how might that work?

🤔 Is there a place where we could add a step to introduce this type of variable behavior? Maybe the step right before?

**Comment by hectorsector** [comment]
Thanks @brianamarie! I've opened separate issues so we can make individual decisions and so the thread doesn't get too long. I'm going to close this out but please feel free to reopen if I missed anything.
