### ISSUE TITLE
Finer grained explanation for %payload.pull_request.title%

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/write-a-ll-course#15]
From #11: 

> We throw '%payload.pull_request.title%' at them without introducing it first. Is there a way we can do two introductions here, or introduce those concepts separately?

>> 🤔 Is there a place where we could add a step to introduce this type of variable behavior? Maybe the step right before?

/cc @brianamarie who brought it up

**Comment by brianamarie** [comment]
This should be addressed in #40 🎉
