### ISSUE TITLE
Replace all octokit uses for suggested changes

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/write-a-ll-course#25]
The `pullRequests.createComment` octokit method is now a [Learning Lab action](https://github.com/github/learning-lab/pull/1020). This course contains some of its use that should be replaced.

![53500915-3d92de80-3a79-11e9-8899-b6ce24ac6348](https://user-images.githubusercontent.com/16547949/62163301-18382400-b2e8-11e9-8a78-72aec5de2035.png)

**Comment by brianamarie** [comment]
This has been addressed in #40
