### ISSUE TITLE
Clarify draft and publish states

### ISSUE THREAD

**Issue by crichID** [githubtraining/write-a-ll-course#28]
Now that authors can create draft courses, can we add them to this course. Some specific talking points:

- Your course is automatically created as a draft
- Drafts can be accessed by anyone who is a repository admin on the course repo
- Drafts allow you to test and refine your course before releasing it to the public
- When you are ready to release your course to the general public and allow any Learning Lab user to register, you will publish the course from the course dashboard

@hectorsector is this something you can tackle?

**Comment by hectorsector** [comment]
I think this is done!

> * Your course is automatically created as a draft
> * Drafts can be accessed by anyone who is a repository admin on the course repo

https://lab.github.com/docs/testing#publish-as-a-draft-course

> * Drafts allow you to test and refine your course before releasing it to the public

https://lab.github.com/docs/testing#test-your-course

> * When you are ready to release your course to the general public and allow any Learning Lab user to register, you will publish the course from the course dashboard

https://lab.github.com/docs/publishing
