### ISSUE TITLE
Update course info to reflect/mention the ability to create User Courses

### ISSUE THREAD

**Issue by JamesMGreene** [githubtraining/write-a-ll-course#34]
@phdumaresq mentioned today while taking this course that the content still suggests that an organization is required to author a course on Learning Lab.

We should update the course's information to reflect/mention the ability to create User Courses.

**Comment by brianamarie** [comment]
This has come up again in the [community forum](https://github.community/t5/GitHub-Learning-Lab/Cannot-access-my-draft-course-404-error/m-p/37826#M1129) 👀

**Comment by brianamarie** [comment]
This has been addressed in the latest audit 🎉 #40
